//
//  gen_globals.h
//  OSXFuzz
//
//  Created by mwr on 23/12/2016.
//
//

#ifndef gen_globals_h
#define gen_globals_h

// TODO: Is there a good way to pull these out dynamically/statically?
const char *iokit_class_names[] = {
    "IOAGPDevice",
    "IOHIDDevice",
    "IOHIDEventService",
    "IOHIDDevice",
    "IOACPIPlatformDevice",
    "IOCardBusDevice",
    "IOHIDDeviceShim",
    "IOAudioStream",
    "IOUSBDevice",
    "IOUSBInterface",
    "IOUSBHostDevice",
    "IOUSBHostDevice",
    "IOADBDevice",
    "ApplePS2Controller",
    "AppleADBKeyboard",
    "IODisplayWrangler",
    "IOGraphicsDevice",
    "OSMetaClassBase",
    "OSMetaClass",
};

// TODO: Pull these out at runtime / static (these base ones are from XNU sources)
const char *iokit_base_properties[] = {
    "IOBSD",
    "BSD Name",
    "BSD Names",
    "BSD Major",
    "BSD Minor",
    "BSD Unit",
    "root-matching",
    "boot-uuid",
    "RAMDisk",
    "IOPrimaryInterruptController",
    "IONWInterrupts",
    "AAPL,interrupts",
    "AAPL,phandle",
    "interrupt-parent",
    "#interrupt-cells",
    "reg",
    "interrupt-controller",
    "interrupt-map",
    "interrupt-map-mask",
    "AAPL,slot-name",
    "slot-names",
    "dma-parent",
    "AAPL,phandle",
    "AppleClamshellState",
    "AppleClamshellCausesSleep",
    "SleepWakeUUID",
    "BootSessionUUID",
    "Standby Enabled",
    "Standby Delay",
    "DestroyFVKeyOnStandby",
    "IOPMResetPowerStateOnWake",
    "DriverPMAssertions",
    "DriverPMAssertionsDetailed",
    "ID",
    "CreatedTime",
    "ModifiedTime",
    "Owner",
    "ServicePtr",
    "RegistryEntryID",
    "Level",
    "Assertions",
    "iommu-id",
    "serial-number",
    "top-level",
    "halt-restart-timeout",
    "system-id",
    "platform-uuid",
    "acpi-device",
    "IOPolledInterface",
    "IOPolledInterfaceActive",
    "IOPolledInterfaceStack",
    "IOKitBuildVersion",
    "IOKitDiagnostics",
    "IORegistryPlanes",
    "IOCatalogue",
    "IOService",
    "IOPower",
    "IODeviceTree",
    "IOAudio",
    "IOFireWire",
    "IOUSB",
    "IORegistryEntryID",
    "IORegistryEntryPropertyKeys",
    "IOService",
    "IOResources",
    "IOClass",
    "IOProbeScore",
    "IOKitDebug",
    "IOProviderClass",
    "IONameMatch",
    "IOPropertyMatch",
    "IOPropertyExistsMatch",
    "IOPathMatch",
    "IOLocationMatch",
    "IOParentMatch",
    "IOResourceMatch",
    "IOResourceMatched",
    "IOMatchedServiceCountMatch",
    "IONameMatched",
    "IOMatchCategory",
    "IODefaultMatchCategory",
    "IOUserClientClass",
    "IOMapperID",
    "IOUserClientCrossEndian",
    "IOUserClientCrossEndianCompatible",
    "IOUserClientSharedInstance",
    "IOUserClientCreator",
    "IOServicePublish",
    "IOServiceFirstPublish",
    "IOServiceMatched",
    "IOServiceFirstMatch",
    "IOServiceTerminate",
    "IOGeneralInterest",
    "IOBusyInterest",
    "IOAppPowerStateInterest",
    "IOPriorityPowerStateInterest",
    "IOPlatformDeviceMessage",
    "IOCFPlugInTypes",
    "IOCommandPoolSize",
    "IOMaximumPriorityCount",
    "IOMaximumBlockCountRead",
    "IOMaximumBlockCountWrite",
    "IOMaximumByteCountRead",
    "IOMaximumByteCountWrite",
    "IOMaximumSegmentCountRead",
    "IOMaximumSegmentCountWrite" ,
    "IOMaximumSegmentByteCountRead" ,
    "IOMaximumSegmentByteCountWrite" ,
    "IOMinimumSegmentAlignmentByteCount",
    "IOMaximumSegmentAddressableBitCount",
    "IOMinimumSaturationByteCount" ,
    "IOIcon",
    "IOBundleResourceFile",
    "IOBusBadge",
    "IODeviceIcon",
    "IOPlatformSerialNumber",
    "IOPlatformUUID",
    "IONVRAM-DELETE-PROPERTY",
    "IONVRAM-SYNCNOW-PROPERTY",
    "IONVRAM-ARMCSR-PROPERTY",
    "aapl,panic-info",
    "IOBootDevice",
    "IOBootDevicePath",
    "IOBootDeviceSize",
    "OS Build Version",
    "IOPMStrictTreeOrder",
    "IGAccelSharedUserClient"
};

const char * iokit_strings[] = {
    "AppleEFINVRAM",
    "AppleSMCClient",
    "IOResources",
    "IOSurfaceRoot",
    "HS01",
    "PDRC",
    "AppleUSBHostLegacyClient",
    "1F,3,0,1,0",
    "AppleBusPowerControllerUSB",
    "SSP3",
    "IOHIDEventSystemUserClient",
    "AppleSMC",
    "com_apple_BootCache",
    "IGAccelCommandQueue",
    "MCHC",
    "SMC",
    "X86PlatformPlugin",
    "AppleHV",
    "CPU3",
    "AppleUSB20HubPort",
    "1D,1",
    "AppleUSBLegacyRoot",
    "Device Management",
    "AppleHSSPIController",
    "14500000",
    "AppleS3XController",
    "IOHDACodecDevice",
    "ADP1",
    "com_vmware_kext_UsbPortArbiter_15_2_0",
    "CPU0",
    "CPU7",
    "CoreStorageLogicalBSDClient",
    "AppleOSXWatchdog",
    "AppleACPIButton",
    "MacBook9,1",
    "AppleACPICPUInterruptController",
    "IOMediaBSDClient",
    "AppleGraphicsDeviceControlClient",
    "Accelerometer",
    "AppleUSB30GLHub",
    "Keyboard / Boot",
    "14100000",
    "PNLF",
    "AppleUSBHostCompositeDevice",
    "DMAC",
    "AirPort_Brcm4360_P2PInterface",
    "PCI0",
    "gpu-control",
    "fec00000",
    "IONVMeBlockStorageDevice",
    "AGPMClient",
    "AppleHPMDevice",
    "15",
    "AppleKeyStore",
    "AppleSmartBattery",
    "AppleLMUController",
    "IGAccel2DContext",
    "AppleHDACodecGeneric",
    "14120000",
    "AppleCamInUserClient",
    "AppleACPIPCI",
    "AppleActuatorDevice",
    "IOBlockStorageDriver",
    "14510000",
    "Recovery HD",
    "com_apple_AppleFSCompression_AppleFSCompressionTypeZlib",
    "en0",
    "AppleAPICInterruptController",
    "14110000",
    "AppleIntelSlowAdaptiveClockingManager",
    "AppleMultitouchDevice",
    "IOSurfaceRootUserClient",
    "Actuator",
    "1F,3,0,1",
    "CMRA",
    "AppleIntelLpssSpiController",
    "IOFramebufferUserClient",
    "FWHD",
    "IOBluetoothHCIController",
    "19",
    "IOUSBHostHIDDevice",
    "AppleUSB20Hub",
    "HDEF",
    "1F",
    "IGAccelDevice",
    "IOFramebufferSharedUserClient",
    "HPM0",
    "Dont_Steal_Mac_OS_X",
    "14110000,0",
    "IOAudioToggleControl",
    "MEM2",
    "SSP1",
    "CPU2",
    "CPU4",
    "3",
    "AppleIntel16X50UARTSync0",
    "bios",
    "AppleVTD",
    "X86PlatformShim",
    "AppleIntelMEClientController",
    "0",
    "SPIT",
    "1E",
    "AppleIntelPCHPMC",
    "AppleIntelFramebuffer",
    "AppleACPIPlatformExpert",
    "com_apple_driver_pmtelemetry",
    "14700000",
    "1F,4",
    "IOHIDResource",
    "IOFramebufferI2CInterface",
    "AppleFDEKeyStoreUserClient",
    "14400000",
    "com_apple_filesystems_hfs",
    "CPU6",
    "AppleKeyStoreUserClient",
    "Root",
    "AppleIntelLpssI2CController",
    "14600000",
    "IOAudioSelectorControl",
    "AppleACPIEventController",
    "IOBluetoothSerialClientSerialStreamSync",
    "15,2",
    "IOAccelDisplayPipeUserClient2",
    "APPLE SSD AP0256J Media",
    "IOAudioLevelControl",
    "AppleActuatorDeviceUserClient",
    "AppleCredentialManager",
    "IOUserEthernetResource",
    "com_vmware_kext_UsbPortArbiterUserClient_15_2_0",
    "AppleEFIRuntime",
    "SMCWatchDogTimer",
    "IntelAccelerator",
    "AppleIntelMEIDriver",
    "SLPB",
    "IOGUIDPartitionScheme",
    "AppleGraphicsDevicePolicy",
    "AppleIntelLpssGspi",
    "MATH",
    "Customer",
    "1",
    "IOAccelerationUserClient",
    "IOHDACodecDriver",
    "IODisplayWrangler",
    "AppleRTC",
    "AppleHDAEngineInput",
    "AudioAUUCDriver",
    "IOService",
    "AppleIntelFramebufferController",
    "CCDataPipe",
    "AppleIntel16X50LPSS",
    "BLTH",
    "CCLogStream",
    "AppleHDADriver",
    "AppleFDEKeyStore",
    "IOHIDEventServiceUserClient",
    "IONetworkStack",
    "AppleMultitouchDeviceUserClient",
    "HS09",
    "com_apple_AppleFSCompression_AppleFSCompressionTypeDataless",
    "IOBluetoothHCIUserClient",
    "IntelFBClientControl",
    "IGAccelGLContext",
    "2",
    "1F,3,0,1,1",
    "AGDPClientControl",
    "CCIOReporterLogStream",
    "AppleHSSPIHIDDriver",
    "CCLogPipe",
    "AppleMCCSParameterHandler",
    "AGPMController",
    "AppleMobileFileIntegrity",
    "AppleACPIEC",
    "io-apic",
    "RTC",
    "URT2",
    "AppleCamIn",
    "XHC1",
    "PWRB",
    "Macintosh HD",
    "AirPort_Brcm4360",
    "IOBluetoothSerialClient",
    "AppleHDAController",
    "AppleHPMLPSS",
    "RP10",
    "AppleBacklightDisplay",
    "LPCB",
    "IGPU",
    "I2C2",
    "ALS0",
    "boot-ec",
    "AppleUSB30HubPort",
    "IOHIDEventDriver",
    "EFI System Partition",
    "USB2.0 Hub",
    "AppleHDAStream",
    "14200000",
    "AppleIntelLpssI2C",
    "IOReportHub",
    "CPU5",
    "AppleECSMBusController",
    "AppleIntelLpssSpiDevice",
    "CoreStoragePhysical",
    "SPI1",
    "IOHIDInterface",
    "AppleACPICPU",
    "AppleACPIACAdapter",
    "1F,2",
    "AppleSmartBatteryManager",
    "SBUS",
    "AppleDeviceManagementHIDEventService",
    "IOHIDSystem",
    "AppleActuatorHIDEventDriver",
    "ARPT",
    "AppleACPILid",
    "HS03",
    "Comfort Mouse 6000",
    "AppleSCSISubsystemGlobals",
    "AppleOSXWatchdogClient",
    "IORootParent",
    "IOSerialBSDClient",
    "RP01",
    "display0",
    "IOPlatformEnabler",
    "IOUSBHostInterface",
    "cpus",
    "IOHIDLibUserClient",
    "70",
    "AppleUpstreamUserClientDriver",
    "AppleMultitouchTrackpadHIDEventDriver",
    "IOHDIXController",
    "AppleGraphicsDeviceControlPlugin",
    "ApplePlatformEnabler",
    "AppleIntelPanelA",
    "AppleUSBHostPacketFilterService",
    "CCDataStream",
    "CCIOReporterDataStream",
    "SSP4",
    "IOAudioEngineUserClient",
    "USB3.0 Hub",
    "14000000",
    "14300000",
    "IOPP",
    "IONetworkStackUserClient",
    "AppleHIDKeyboardEventDriverV2",
    "IGAccelSurface",
    "URT0",
    "AppleSMBIOS",
    "CPU1",
    "IOHIDParamUserClient",
    "AGPM",
    "AppleBroadcomBluetoothHostController",
    "USB-C Digital AV Multiport Adapter",
    "Apple Internal Keyboard / Trackpad",
    "AppleUSBXHCI",
    "AppleUSBInterface",
    "IGAccelSharedUserClient",
    "SMB0",
    "1D",
    "1F,3,0",
    "IOHDACodecFunction",
    "HS04",
    "IOBluetoothSerialManager",
    "pci8086,9d60",
    "LDRC",
    "RootDomainUserClient",
    "AppleMCCSControlModule",
    "IPIC",
    "Google Chrome",
    "AppleUSBHostResources",
    "LID0",
    "14",
    "Apple Inc.",
    "Trackpad / Boot",
    "IMEI",
    "IOAudioControlUserClient",
    "1F,3",
    "RP09",
    "AppleIntel16X50UARTSync2",
    "1C",
    "com_apple_filesystems_hfs_encodings",
    "IOPCIMessagedInterruptController",
    "Root Hub Simulation Simulation",
    "TIMR",
    "IOPMrootDomain",
    "SSD0",
    "IOBluetoothHostControllerUARTTransport",
    "AGPMEnabler",
    "SBS0",
    "PMCR",
    "IOReportUserClient",
    "16",
    "EC",
    "IOHIDUserClient",
    "AppleHDAEngineOutput",
    "CoreStorage",
    "1E,3"
};

const char * random_classname()
{
    unsigned int n = sizeof(iokit_class_names) / sizeof(iokit_class_names[0]);
    int idx = rand() % n;
    const char *str = iokit_class_names[idx];
    return str;
}

const char * random_property_key()
{
    unsigned int n = sizeof(iokit_base_properties) / sizeof(iokit_base_properties[0]);
    int idx = rand() % n;
    const char *str = iokit_base_properties[idx];
    return str;
}

const char * random_property_value()
{
    unsigned int n = sizeof(iokit_strings) / sizeof(iokit_strings[0]);
    int idx = rand() % n;
    const char *str = iokit_strings[idx];
    return str;
}

#endif /* gen_globals_h */
